### ISSUE TITLE
CDMGraphVisualizer.py KeyError: 'type'

### ISSUE THREAD

**Issue by UnnameBao** [raytheonbbn/tc-ta3-api-bindings-python#2]
When I try use CDMGraphVisualizer.py to visualize testdata, I found this error:
> Traceback (most recent call last):
  File "CDMGraphVisualizer.py", line 232, in <module>
    main()
  File "CDMGraphVisualizer.py", line 180, in main
    rtype = cdmparser.get_record_type(edge)
  File "/home/b0ring/anaconda3/envs/py27/lib/python2.7/site-packages/tc/schema/records/parsing.py", line 79, in get_record_type
    if record["type"] == self._type_checks[type_]:
KeyError: 'type'

I tried to fix this problem to modifiy parsing.py in line 79 to:
> if record["datum"]["type"] == self._type_checks[type_]:

but then I got a new error:
> Traceback (most recent call last):
  File "CDMGraphVisualizer.py", line 232, in <module>
    main()
  File "CDMGraphVisualizer.py", line 180, in main
    rtype = cdmparser.get_record_type(edge)
  File "/home/b0ring/anaconda3/envs/py27/lib/python2.7/site-packages/tc/schema/records/parsing.py", line 86, in get_record_type
    raise ValueError("Provided record type not supported by CDM Parser.")
ValueError: Provided record type not supported by CDM Parser.

Since I use testdata rather than use my own data, I thought there has problem at this script.

**Comment by Endcat** [comment]
> When I try use CDMGraphVisualizer.py to visualize testdata, I found this error:
> 
> > Traceback (most recent call last):
> > File "CDMGraphVisualizer.py", line 232, in 
> > main()
> > File "CDMGraphVisualizer.py", line 180, in main
> > rtype = cdmparser.get_record_type(edge)
> > File "/home/b0ring/anaconda3/envs/py27/lib/python2.7/site-packages/tc/schema/records/parsing.py", line 79, in get_record_type
> > if record["type"] == self._type_checks[type_]:
> > KeyError: 'type'
> 
> I tried to fix this problem to modifiy parsing.py in line 79 to:
> 
> > if record["datum"]["type"] == self._type_checks[type_]:
> 
> but then I got a new error:
> 
> > Traceback (most recent call last):
> > File "CDMGraphVisualizer.py", line 232, in 
> > main()
> > File "CDMGraphVisualizer.py", line 180, in main
> > rtype = cdmparser.get_record_type(edge)
> > File "/home/b0ring/anaconda3/envs/py27/lib/python2.7/site-packages/tc/schema/records/parsing.py", line 86, in get_record_type
> > raise ValueError("Provided record type not supported by CDM Parser.")
> > ValueError: Provided record type not supported by CDM Parser.
> 
> Since I use testdata rather than use my own data, I thought there has problem at this script.

I think the script works well for me, but not the given testdata.
The script works fine with darpa tc datasets, since you can replace the testdata. There are still missing key-values in
https://github.com/raytheonbbn/tc-ta3-api-bindings-python/blob/8cd25dc46b5c6f7fd86cd4bbf6d512a7bfbef8e9/tools/CDMGraphVisualizer.py#L51C24-L51C24
NodeEdgeShapesColors dict which need to fix it according to errors.
btw, graphviz is too week to generate a large CDM graph, it crashed my pc every time :<
